name: Run Tests
run-name: ${{ github.actor }} pushed a change 🚀
on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Use Python Cache
        uses: actions/cache@v3
        with:
          path: |
            .venv
            .tox
            .mypy_cache
          key: python-${{ matrix.python }}-${{ hashFiles('setup.py', 'requirements_*.txt') }}
          restore-keys: |
            test-${{ matrix.python }}-${{ hashFiles('setup.py', 'requirements_*.txt') }}
            test-${{ matrix.python }}-
      - name: Install Dev Environment
        run: |
          . ./scripts/venv_github.sh
          # it's not necessary to install the whole dev-environment to run tox.  However, this is a good check
          # that the dev-setup works in all python versions
          ./scripts/setup_dev_env.sh
      - name: Run Tox
        # Run tox using the version of Python in `PATH`
        run: |
          . ./scripts/venv_github.sh
          ./scripts/tox_github.sh "${{ matrix.python }}"
      - name: Use PyBugsAI Cache
        if: ${{ matrix.python == '3.11' }}
        uses: actions/cache@v3
        with:
          path: |
            .pybugsai
          key:
            pybugsai-${{ hashFiles('**/*.py') }}
          restore-keys: |
            pybugsai-${{ hashFiles('**/*.py') }}
            pybugsai-
      - name: Run PyBugsAI
        if: ${{ matrix.python == '3.11' }}
        run: |
          . ./scripts/venv_github.sh
          ./scripts/pybugsai_github.sh
  results:
      if: ${{ always() }}
      runs-on: ubuntu-latest
      name: Final Results
      needs: [test]
      steps:
          - run: |
              [[ "${{ needs.tox.result }}" == "success" ]] && [[ "${{ needs.pybugsai.result }}" == "success" ]]
